language: go
branches:
  only:
  - master
sudo: false
before_install:
  - go get github.com/mattn/goveralls
  - go get -t ./...
script:
  - go test ./retrodep/glide -v
  - go test ./retrodep -v -covermode=count -coverprofile=profile.cov
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
notifications:
  email: false
